name: Build Check

on:
    push:
        branches:
            - "**"
    pull_request:

jobs:
    get-commits:
        runs-on: ubuntu-latest
        outputs:
            commits: ${{ steps.set-commits.outputs.commits }}
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - id: set-commits
              run: |
                  COMMITS=$(git rev-list ${{ github.event.before }}..${{ github.event.after }} --reverse)
                  JSON=$(echo "$COMMITS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
                  echo "commits=$JSON" >> "$GITHUB_OUTPUT"

    l3build:
        needs: get-commits
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                commit: ${{ fromJSON(needs.get-commits.outputs.commits) }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Switch to commit
              run: git checkout ${{ matrix.commit }}
            - uses: zauguin/install-texlive@v4
              with:
                  package_file: .github/tl_packages
            - run: l3build doc
