name: Build Check

on:
    push:

jobs:
    get-commits:
        runs-on: ubuntu-latest
        outputs:
            commits: ${{ steps.set-commits.outputs.commits }}
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - id: set-commits
              shell: bash
              run: |
                  COMMITS=$(git rev-list ${{ github.event.before }}..${{ github.event.after }} --reverse)
                  JSON=$(printf '%s\n' "$COMMITS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
                  echo "commits=$JSON" >> "$GITHUB_OUTPUT"

    l3build:
        needs: get-commits
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                commit: ${{ fromJSON(needs.get-commits.outputs.commits) }}
        steps:
            - uses: actions/checkout@v6
              with:
                  ref: ${{ matrix.commit }}

            - uses: zauguin/install-texlive@v4
              with:
                  package_file: .github/tl_packages

            - run: l3build doc
